In [59]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import numpy as np

from datetime import datetime

matplotlib.rc('font', family = 'Noto Sans CJK JP')
matplotlib.rc('axes', unicode_minus = False)

plt.style.use(['fivethirtyeight'])


import seaborn as sns



from scipy import stats
import scipy.stats
from scipy.stats import shapiro
from scipy.stats import bartlett, levene
from statsmodels.formula.api import ols
from statsmodels.api import qqplot, add_constant
import statsmodels.formula.api as smf
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFE
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
from statsmodels.tools.eval_measures import rmse
from statsmodels.stats.proportion import proportions_ztest

from sklearn.tree import export_graphviz

import graphviz
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from IPython.core.display import display, HTML
from sklearn.cluster import KMeans
from yellowbrick.cluster import KElbowVisualizer
from scipy.spatial.distance import cdist
from scipy.cluster.hierarchy import linkage, dendrogram, fcluster
from sklearn.cluster import AgglomerativeClustering,KMeans, DBSCAN
from sklearn.metrics import silhouette_samples, silhouette_score
from yellowbrick.cluster import SilhouetteVisualizer
from dask.diagnostics import ProgressBar
import statsmodels.api as sm
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn import metrics
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score, f1_score
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, f1_score, f1_score, roc_curve, auc, precision_score,recall_score


display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
df = pd.read_csv('final_merged_dataset.csv')

In [3]:
df

,No_Die,Ox_Chamber,process,type,Temp_OXid,Vapor,ppm,Pressure,Oxid_time,thickness,...,Furance_Temp,RTA_Temp,count_ion,Target,Error_message,Wafer_map,chamber_total_count,chamber_path,defective,defective_chip_rate
0,NOLSM325131325,2,Oxidation,dry,1214.307948,O2,26.69,0.203,120,713.132,...,854.0,154,582,141,none,[[0 0 0 0 0 0 0 0 0 0 1 2 1 1 1 2 0 0 0 0 0 0 ...,2907,21111,0,0.0705
1,NOLSM326132326,2,Oxidation,dry,978.110792,O2,30.86,0.217,137,714.295,...,895.0,156,542,55,none,[[0 0 0 0 0 0 0 0 0 0 2 2 2 2 1 2 0 0 0 0 0 0 ...,2819,21122,0,0.0275
2,NOLSM327133327,2,Oxidation,dry,1176.019149,O2,31.07,0.218,116,710.114,...,898.0,152,550,96,none,[[0 0 0 0 0 0 0 0 0 0 1 2 1 1 1 2 0 0 0 0 0 0 ...,2847,21133,0,0.0480
3,NOLSM328134328,2,Oxidation,dry,933.442733,O2,31.04,0.196,143,710.617,...,879.0,155,582,105,none,[[0 0 0 0 0 0 0 0 0 0 2 1 1 1 1 2 0 0 0 0 0 0 ...,2907,21111,0,0.0525
4,NOLSM329135329,2,Oxidation,wet,1140.598752,H2O,31.37,0.215,76,711.632,...,882.0,155,542,79,none,[[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 ...,2819,21122,0,0.0395
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1653,NOLSM3081211,1,Oxidation,dry,1160.350439,O2,34.56,0.199,18,710.197,...,883.0,153,582,105,none,[[0 0 0 0 0 0 0 0 0 0 1 2 2 1 1 1 0 0 0 0 0 0 ...,2902,13311,0,0.0525
1654,NOLSM8493212,1,Oxidation,wet,1268.105427,H2O,45.07,0.215,22,707.179,...,867.0,152,550,42,none,[[0 0 0 0 0 0 0 0 0 0 2 2 2 2 1 1 0 0 0 0 0 0 ...,2878,11133,0,0.0210
1655,NOLSM8503213,1,Oxidation,wet,1279.160563,H2O,45.12,0.214,21,712.946,...,868.0,152,542,42,none,[[0 0 0 0 0 0 0 0 0 0 1 1 1 1 2 1 0 0 0 0 0 0 ...,2821,11222,0,0.0210
1656,NOLSM8513214,1,Oxidation,wet,1272.804948,H2O,45.34,0.213,20,711.987,...,868.0,152,582,24,none,[[0 0 0 0 0 0 0 0 0 0 2 1 2 2 2 1 0 0 0 0 0 0 ...,2938,11311,0,0.0120
1657,NOLSM8523215,1,Oxidation,wet,1278.097085,H2O,45.26,0.215,22,716.238,...,868.0,152,582,84,none,[[0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 1 0 0 0 0 0 0 ...,2917,12111,0,0.0420

In [10]:
df.columns

Index(['No_Die', 'Ox_Chamber', 'process', 'type', 'Temp_OXid', 'Vapor', 'ppm',
       'Pressure', 'Oxid_time', 'thickness', 'Lot_Num', 'Wafer_Num',
       'Datetime', 'count_oxid', 'photo_soft_Chamber', 'process 2',
       'resist_target', 'N2_HMDS', 'pressure_HMDS', 'temp_HMDS',
       'temp_HMDS_bake', 'time_HMDS_bake', 'spin1', 'spin2', 'spin3',
       'photoresist_bake', 'temp_softbake', 'time_softbake', 'count_soft',
       'lithography_Chamber', 'Process 2-1', 'Line_CD', 'UV_type',
       'Wavelength', 'Resolution', 'Energy_Exposure', 'count_litho',
       'Etching_Chamber', 'Process 3', 'Thin F4', 'Thin F3', 'Thin F2',
       'Thin F1', 'Temp_Etching', 'Source_Power', 'Selectivity',
       'count_etching', 'Chamber_Num', 'process4', 'Flux60s', 'Flux90s',
       'Flux160s', 'Flux480s', 'Flux840s', 'input_Energy', 'Temp_implantation',
       'Furance_Temp', 'RTA_Temp', 'count_ion', 'Target', 'Error_message',
       'Wafer_map', 'chamber_total_count', 'chamber_path', 'defective',
       'defective_chip_rate'],
      dtype='object')

In [11]:
df.chamber_path.unique()

array([21111, 21122, 21133, 21222, 21233, 21211, 21311, 21322, 21333,
       22111, 22222, 22333, 23133, 23222, 23311, 22122, 22133, 22211,
       22233, 22311, 22322, 23111, 23333, 23122, 23211, 23233, 23322,
       33311, 31111, 31333, 32133, 32222, 32311, 33111, 33222, 33333,
       31133, 31222, 31311, 32111, 33133, 31122, 31211, 31233, 31322,
       32122, 32211, 32233, 32322, 32333, 33122, 33211, 33233, 33322,
       11111, 11222, 11333, 12133, 12222, 12311, 13111, 11311, 12111,
       12333, 13222, 13333, 11133, 13133, 13311, 11122, 11211, 11233,
       11322, 12122, 12211, 12233, 12322, 13122, 13211, 13233, 13322])

In [12]:
temp_cnt_chamber_path = df[['No_Die', 'chamber_total_count', 'chamber_path','Target','defective_chip_rate']];temp_cnt_chamber_path

,No_Die,chamber_total_count,chamber_path,Target,defective_chip_rate
0,NOLSM325131325,2907,21111,141,0.0705
1,NOLSM326132326,2819,21122,55,0.0275
2,NOLSM327133327,2847,21133,96,0.0480
3,NOLSM328134328,2907,21111,105,0.0525
4,NOLSM329135329,2819,21122,79,0.0395
...,...,...,...,...,...
1653,NOLSM3081211,2902,13311,105,0.0525
1654,NOLSM8493212,2878,11133,42,0.0210
1655,NOLSM8503213,2821,11222,42,0.0210
1656,NOLSM8513214,2938,11311,24,0.0120
1657,NOLSM8523215,2917,12111,84,0.0420

In [43]:
temp_df = temp_cnt_chamber_path.groupby(['chamber_path','chamber_total_count'])['defective_chip_rate','Target'].mean().reset_index();temp_df

/tmp/ipykernel_10836/2244145357.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  temp_df = temp_cnt_chamber_path.groupby(['chamber_path','chamber_total_count'])['defective_chip_rate','Target'].mean().reset_index();temp_df

    chamber_path  chamber_total_count  defective_chip_rate      Target
0          11111                 2938             0.046603   93.206897
1          11122                 2850             0.041167   82.333333
2          11133                 2878             0.048268   96.535714
3          11211                 2909             0.059958  119.916667
4          11222                 2821             0.047423   94.846154
..           ...                  ...                  ...         ...
76         33222                 2704             0.037132   74.264706
77         33233                 2732             0.045111   90.222222
78         33311                 2821             0.044250   88.500000
79         33322                 2733             0.033389   66.777778
80         33333                 2761             0.048720   97.440000

[81 rows x 4 columns]

# chi2검정

In [69]:
temp_df = temp_df.sort_values(by = 'chamber_total_count');temp_df

    chamber_path  chamber_total_count  defective_chip_rate      Target
76         33222                 2704             0.037132   74.264706
67         32222                 2719             0.055452  110.904762
77         33233                 2732             0.045111   90.222222
73         33122                 2733             0.033167   66.333333
79         33322                 2733             0.033389   66.777778
..           ...                  ...                  ...         ...
3          11211                 2909             0.059958  119.916667
9          12111                 2917             0.046914   93.827586
15         12311                 2917             0.048431   96.862069
6          11311                 2938             0.044875   89.750000
0          11111                 2938             0.046603   93.206897

[81 rows x 4 columns]

In [70]:
small_cnt_path_list  = list(temp_df.head(5).chamber_path.values)
many_cnt_path_list  = list(temp_df.tail(5).chamber_path.values)

In [71]:
small_cnt_path_df = temp_df.query('chamber_path in @small_cnt_path_list');small_cnt_path_df

    chamber_path  chamber_total_count  defective_chip_rate      Target
76         33222                 2704             0.037132   74.264706
67         32222                 2719             0.055452  110.904762
77         33233                 2732             0.045111   90.222222
73         33122                 2733             0.033167   66.333333
79         33322                 2733             0.033389   66.777778

In [72]:
many_cnt_path_df = temp_df.query('chamber_path in @many_cnt_path_list');many_cnt_path_df

    chamber_path  chamber_total_count  defective_chip_rate      Target
3          11211                 2909             0.059958  119.916667
9          12111                 2917             0.046914   93.827586
15         12311                 2917             0.048431   96.862069
6          11311                 2938             0.044875   89.750000
0          11111                 2938             0.046603   93.206897

In [73]:
aaa = pd.DataFrame({'0': [small_cnt_path_df.Target.mean(), 2000-small_cnt_path_df.Target.mean()], '1' : [many_cnt_path_df.Target.mean(),2000-many_cnt_path_df.Target.mean()]})

chi,pval,dof,expected = stats.chi2_contingency(aaa.T)

print('chi-square test')
print('chi-sq: {0:0.3f}'.format(chi))
print('p: {0:0.3f}'.format(pval))

chi-square test
chi-sq: 1.488
p: 0.222

# 2 proportion test

In [74]:
temp_df = temp_df.sort_values(by = 'chamber_total_count');temp_df

    chamber_path  chamber_total_count  defective_chip_rate      Target
76         33222                 2704             0.037132   74.264706
67         32222                 2719             0.055452  110.904762
77         33233                 2732             0.045111   90.222222
73         33122                 2733             0.033167   66.333333
79         33322                 2733             0.033389   66.777778
..           ...                  ...                  ...         ...
3          11211                 2909             0.059958  119.916667
9          12111                 2917             0.046914   93.827586
15         12311                 2917             0.048431   96.862069
6          11311                 2938             0.044875   89.750000
0          11111                 2938             0.046603   93.206897

[81 rows x 4 columns]

In [75]:
small_cnt_path_list  = list(temp_df.head(5).chamber_path.values)
many_cnt_path_list  = list(temp_df.tail(5).chamber_path.values)